import type { Metadata } from "next";
import "./globals.css";
import "@/shares/styles/mdeditor.css";
import { StyledComponentsRegistry } from "@/shares/lib/registry";

export const metadata: Metadata = {
  title: "MyLog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
